version: '3.9'

networks:
  twodave:

services:
  php:
    build: .
    platform: linux/amd64
    container_name: twodave
    networks:
      - twodave
    ports:
      - "3000:80"
    volumes:
      - .:/var/www/html

  mysql:
    image: mysql:5.7
    platform: linux/amd64
    container_name: twodavedb
    networks:
      - twodave
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=R00tPassw0rd!1
      - MYSQL_DATABASE=twodave
      - MYSQL_USER=twodave
      - MYSQL_PASSWORD=Passw0rd!1
    volumes:
      - ./.docker/mysql:/var/lib/mysql