version: '3.9'

services:
  app:
    build: .
    platform: linux/amd64
    ports:
      - 3000:80
    volumes:
      - ./:/var/www/html/

  db:
    image: mysql:5.7
    platform: linux/amd64
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=R00tPassw0rd
      - MYSQL_DATABASE=2dave
      - MYSQL_USER=2dave
      - MYSQL_PASSWORD=2davePassw0rd
    volumes:
      - ./.mysql/:/var/lib/mysql/
