services:
  app:
    build: .
    platform: linux/amd64
    container_name: twodave
    ports:
      - 3000:80
    networks:
      - twodave
    volumes:
      - ./:/var/www/html
      - ./apache.conf:/etc/apache2/sites-available/000-default.conf

  data:
    image: postgres:16.4
    platform: linux/amd64
    container_name: twodave-data
    networks:
      - twodave
    environment:
      POSTGRES_DB: twodave
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - twodave-data:/var/lib/postgresql/data

networks:
  twodave:


volumes:
  twodave-data:
